name: mi1lion
favicon: null
layout_spectrum: 0.8049877942539752
typography_spectrum: 0.7551591396331787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7106608278118074
  lightness: 0.1836788619402796
  saturation: 0.7664143559522927
  rhythmicContrast: 0.3001896715722978
purpose: []
